language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - rbx-2
  - jruby-head
jdk:
  - oraclejdk7
  - openjdk7
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.1.0
      jdk: openjdk7
    - rvm: rbx-2
      jdk: openjdk7

before_install: sh ./before_install.sh

